name: Auto Build Deploy Client
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSHPASS
        run: sshpass -p ${{ secrets.SSH_PASS }} ssh -o 'StrictHostKeyChecking no' -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /kmp/rithy.org && git checkout main && git pull && pnpm i && pnpm run build && pm2 restart 48'
